import type { Channel } from "./types"

export interface CountryChannels {
  name: string
  code: string
  emoji: string
  channels: Channel[]
}

export const GLOBAL_CHANNELS: Channel[] = [
  // UK Channels
  {
    id: "bbc-news-global",
    name: "BBC News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/BBC_News_2019.svg/1200px-BBC_News_2019.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ sectionsdelay/2/vprv/1/playlist_type/DVR/mediacodec/h.264/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/9Auq9mYxFEE/title/BBC%20News/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37%2C18%2C19%2C34%2C35%2C36%2C37%2C18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "GB",
    language: "English",
    isLive: true,
    globalCategory: "UK",
  },
  {
    id: "bbc-one-uk",
    name: "BBC One",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/BBC_One_logo_2021.svg/1200px-BBC_One_logo_2021.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/test/title/BBC%20One/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "GB",
    language: "English",
    isLive: true,
    globalCategory: "UK",
  },
  {
    id: "itv-uk",
    name: "ITV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/ITV_2013.svg/1200px-ITV_2013.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/test/title/ITV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "GB",
    language: "English",
    isLive: true,
    globalCategory: "UK",
  },

  // USA Channels
  {
    id: "cnn-global",
    name: "CNN",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/CNN_International_sans_border.svg/1200px-CNN_International_sans_border.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/jfKfPfyJRdk/title/CNN%20Live/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
  },
  {
    id: "fox-news-usa",
    name: "Fox News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/FOX_News_Channel_logo.svg/1200px-FOX_News_Channel_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/test/title/Fox%20News/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
  },
  {
    id: "espn-usa",
    name: "ESPN",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/ESPN_logo.svg/1200px-ESPN_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/ESPN/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Sports",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
  },
  {
    id: "nbc-usa",
    name: "NBC",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/NBC_logo.svg/1200px-NBC_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/NBC/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
  },

  // France Channels
  {
    id: "france24-global",
    name: "France 24",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Logo-france-24.png/1200px-Logo-france-24.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/Fmjxz5iFhvA/title/France24%20English/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "FR",
    language: "English",
    isLive: true,
    globalCategory: "France",
  },
  {
    id: "france2-fr",
    name: "France 2",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/France_2_logo_2013.svg/1200px-France_2_logo_2013.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/France%202/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "FR",
    language: "French",
    isLive: true,
    globalCategory: "France",
  },
  {
    id: "tf1-fr",
    name: "TF1",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/TF1_logo_2013.svg/1200px-TF1_logo_2013.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/TF1/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "FR",
    language: "French",
    isLive: true,
    globalCategory: "France",
  },

  // Germany Channels
  {
    id: "dw-news-global",
    name: "DW News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/DW_English_2012_logo.svg/1200px-DW_English_2012_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn/test/rbufm/0/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/IhgQOlCN7Jw/title/DW%20English/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "DE",
    language: "English",
    isLive: true,
    globalCategory: "Germany",
  },
  {
    id: "zdf-de",
    name: "ZDF",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/ZDF_logo.svg/1200px-ZDF_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/ZDF/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "DE",
    language: "German",
    isLive: true,
    globalCategory: "Germany",
  },
  {
    id: "ard-de",
    name: "ARD",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/ARD.svg/1200px-ARD.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/ARD/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "DE",
    language: "German",
    isLive: true,
    globalCategory: "Germany",
  },

  // Middle East Channels
  {
    id: "al-jazeera-global",
    name: "Al Jazeera",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Al_Jazeera_English_2016_logo.svg/1200px-Al_Jazeera_English_2016_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type,mediacodec/sig/test/video_id/gCNeDWCI0vo/title/Al%20Jazeera%20English/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "QA",
    language: "English",
    isLive: true,
    globalCategory: "Middle East",
  },
  {
    id: "mbc-me",
    name: "MBC",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/MBC_ME_logo.svg/1200px-MBC_ME_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/MBC/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "AE",
    language: "Arabic",
    isLive: true,
    globalCategory: "Middle East",
  },
  {
    id: "rotana-me",
    name: "Rotana",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Rotana_logo.svg/1200px-Rotana_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/Rotana/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "SA",
    language: "Arabic",
    isLive: true,
    globalCategory: "Middle East",
  },

  // Pakistan Channels
  {
    id: "ary-news-pk",
    name: "ARY News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/ARY_News.svg/1200px-ARY_News.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/ARY%20News/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "PK",
    language: "Urdu",
    isLive: true,
    globalCategory: "Pakistan",
  },
  {
    id: "geo-pk",
    name: "GEO News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/GEO_News_logo.svg/1200px-GEO_News_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/GEO%20News/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "PK",
    language: "Urdu",
    isLive: true,
    globalCategory: "Pakistan",
  },
  {
    id: "ptv-pk",
    name: "PTV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/PTV_Logo_2014.svg/1200px-PTV_Logo_2014.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/PTV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "PK",
    language: "Urdu",
    isLive: true,
    globalCategory: "Pakistan",
  },

  // Bangladesh Channels
  {
    id: "btv-bd",
    name: "BTV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Bangladesh_Television_Logo.svg/1200px-Bangladesh_Television_Logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/BTV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "BD",
    language: "Bengali",
    isLive: true,
    globalCategory: "Bangladesh",
  },
  {
    id: "channel-i-bd",
    name: "Channel i",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Channel_I_logo.svg/1200px-Channel_I_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/Channel%20I/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "BD",
    language: "Bengali",
    isLive: true,
    globalCategory: "Bangladesh",
  },
  {
    id: "ekattor-bd",
    name: "Ekattor TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Ekattor_TV_logo.png/1200px-Ekattor_TV_logo.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/Ekattor%20TV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "BD",
    language: "Bengali",
    isLive: true,
    globalCategory: "Bangladesh",
  },

  // India Channels (existing)
  {
    id: "india-ndtv",
    name: "NDTV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/NDTV_logo.svg/1200px-NDTV_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/NDTV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
  },
  {
    id: "india-aaj-tak",
    name: "Aaj Tak",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Aaj_Tak_logo.svg/1200px-Aaj_Tak_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv,playlist_type/mediacodec/sig/test/video_id/test/title/Aaj%20Tak/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
  },
  {
    id: "india-sony",
    name: "Sony TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Sony_Entertainment_Television_India_Logo.svg/1200px-Sony_Entertainment_Television_India_Logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv/playlist_type/mediacodec/sig/test/video_id/test/title/Sony%20TV/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
  },
  {
    id: "india-star-plus",
    name: "Star Plus",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Star_Plus_logo.svg/1200px-Star_Plus_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv/playlist_type/mediacodec/sig/test/video_id/test/title/Star%20Plus/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
  },
  {
    id: "india-star-sports",
    name: "Star Sports",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Star_Sports_logo.svg/1200px-Star_Sports_logo.svg.png",
    url: "https://manifest.googlevideo.com/api/manifest/hls_variant/expire/1704067200/ei/test/ip/0.0.0.0/ipbits/0/source/youtube/client/tv-html5/req_proto/https/rn/test/rbuf/0/ractk/1/vprv/1/playlist_type/DVR/mediacodec/h.264,vp9/sparams/expire,ei,ip,ipbits,source,client,req_proto,rn,rbuf,ractk,rbufm,vprv/playlist_type/mediacodec/sig/test/video_id/test/title/Star%20Sports/urlversion/6/formats/18%2C19%2C34%2C35%2C36%2C37",
    category: "Sports",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
  },
]

// Country groups configuration
export const COUNTRIES: CountryChannels[] = [
  {
    name: "India",
    code: "IN",
    emoji: "🇮🇳",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "India"),
  },
  {
    name: "USA",
    code: "US",
    emoji: "🇺🇸",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "USA"),
  },
  {
    name: "UK",
    code: "GB",
    emoji: "🇬🇧",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "UK"),
  },
  {
    name: "France",
    code: "FR",
    emoji: "🇫🇷",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "France"),
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "🇩🇪",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Germany"),
  },
  {
    name: "Pakistan",
    code: "PK",
    emoji: "🇵🇰",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Pakistan"),
  },
  {
    name: "Bangladesh",
    code: "BD",
    emoji: "🇧🇩",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Bangladesh"),
  },
  {
    name: "Middle East",
    code: "ME",
    emoji: "🌍",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Middle East"),
  },
]
