import type { Channel } from "./types"

export interface CountryChannels {
  name: string
  code: string
  emoji: string
  channels: Channel[]
}

export const GLOBAL_CHANNELS: Channel[] = [
  // ================= INDIA CHANNELS =================
  {
    id: "aaj-tak-india",
    name: "Aaj Tak",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Aaj_Tak_logo.svg/1200px-Aaj_Tak_logo.svg.png",
    url: "https://feeds.intoday.in/aajtak/api/livetv-video/index.m3u8",
    backupUrl: "https://d1385oiprd2i1z.cloudfront.net/out/v1/4b99818817a048e58f2be4889c4458d6/index.m3u8",
    youtubeId: "Nq2wYlWFucg",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "ndtv-india",
    name: "NDTV India",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/NDTV_logo.svg/1200px-NDTV_logo.svg.png",
    url: "https://ndtvindiaelemarchana.akamaized.net/hls/live/2003679/ndtvindia/ndtvindiamaster.m3u8",
    backupUrl: "https://ndtv24x7elemarchana.akamaized.net/hls/live/2003678/ndtv24x7/ndtv24x7master.m3u8",
    youtubeId: "l9ViEIip984",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "india-today-live",
    name: "India Today",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/India_Today_logo.svg/1200px-India_Today_logo.svg.png",
    url: "https://indiatodaylive.akamaized.net/hls/live/2014320/indiatoday/indiatodaylive/master.m3u8",
    youtubeId: "0b_e_5R9Rz8",
    category: "News",
    country: "IN",
    language: "English",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "sansad-tv-india",
    name: "Sansad TV (Parliament)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Sansad_TV_logo.png/640px-Sansad_TV_logo.png",
    url: "https://loksabhatv.akamaized.net/hls/live/2012753/lstv/master.m3u8",
    category: "Government",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "dd-national-india",
    name: "DD National",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/DD_National_2023.svg/1200px-DD_National_2023.svg.png",
    url: "https://ddnational.akamaized.net/hls/live/2012754/ddnational/master.m3u8",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "dd-sports-india",
    name: "DD Sports",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/DD_Sports_2023.svg/1200px-DD_Sports_2023.svg.png",
    url: "https://ddsports.akamaized.net/hls/live/2012755/ddsports/master.m3u8",
    category: "Sports",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "republic-bharat",
    name: "Republic Bharat",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Republic_Bharat_Logo.png/640px-Republic_Bharat_Logo.png",
    url: "https://stream.bharat.republicworld.com/live/r_bharat_live/index.m3u8",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "abp-news-india",
    name: "ABP News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/ABP_News_logo_2020.svg/1200px-ABP_News_logo_2020.svg.png",
    url: "https://abp-i.akamaized.net/hls/live/765529/abpnews/master.m3u8",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "9xm-music-india",
    name: "9XM Bollywood Music",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/9XM_logo.svg/1200px-9XM_logo.svg.png",
    url: "https://d2q8p4pe5spbak.cloudfront.net/bpk-tv/9XM/default/index.m3u8",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "b4u-music-india",
    name: "B4U Music",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/9/90/B4U_Music_2020.svg/1200px-B4U_Music_2020.svg.png",
    url: "https://b4umusic-origin.akamaized.net/hls/live/2027209/b4umusic/master.m3u8",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "mastiii-music-india",
    name: "Mastiii TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Mastiii_logo.png/640px-Mastiii_logo.png",
    url: "https://mastiiilive.akamaized.net/hls/live/2021531/mastiii/master.m3u8",
    category: "Entertainment",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },
  {
    id: "news24-india",
    name: "News 24",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/News24_logo.png/640px-News24_logo.png",
    url: "https://news24live.akamaized.net/hls/live/2022718/news24/master.m3u8",
    category: "News",
    country: "IN",
    language: "Hindi",
    isLive: true,
    globalCategory: "India",
    streamType: "hls",
  },

  // ================= USA CHANNELS =================
  {
    id: "nasa-tv-usa",
    name: "NASA TV HD",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/NASA_logo.svg/1200px-NASA_logo.svg.png",
    url: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    category: "Science",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
    streamType: "hls",
  },
  {
    id: "bloomberg-us",
    name: "Bloomberg TV",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Bloomberg_Television_logo_2019.svg/1200px-Bloomberg_Television_logo_2019.svg.png",
    url: "https://bloomberg.akamaized.net/hls/live/2014325/bloomberg/master.m3u8",
    youtubeId: "dp8PhLsUcFE",
    category: "News",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
    streamType: "hls",
  },
  {
    id: "redbull-tv-sports",
    name: "Red Bull TV Sports",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Red_Bull_TV_logo.svg/1200px-Red_Bull_TV_logo.svg.png",
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
    category: "Sports",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
    streamType: "hls",
  },
  {
    id: "rakuten-action-movies",
    name: "Rakuten Action Movies",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Rakuten_TV_logo.svg/1200px-Rakuten_TV_logo.svg.png",
    url: "https://rakuten-actionmovies-1-eu.rakuten.wurl.tv/playlist.m3u8",
    category: "Entertainment",
    country: "US",
    language: "English",
    isLive: true,
    globalCategory: "USA",
    streamType: "hls",
  },

  // ================= UK CHANNELS =================
  {
    id: "sky-news-uk",
    name: "Sky News UK",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Sky_News_logo_2020.svg/1200px-Sky_News_logo_2020.svg.png",
    url: "https://skynews-live.akamaized.net/hls/live/2002889/skynews/master.m3u8",
    youtubeId: "9Auq9mYxFEE",
    category: "News",
    country: "GB",
    language: "English",
    isLive: true,
    globalCategory: "UK",
    streamType: "hls",
  },
  {
    id: "euronews-uk",
    name: "Euronews Global",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Euronews_2016_logo.svg/1200px-Euronews_2016_logo.svg.png",
    url: "https://euronews-euronews-world-1-gb.samsung.wurl.tv/playlist.m3u8",
    youtubeId: "pykpO5kQJ98",
    category: "News",
    country: "GB",
    language: "English",
    isLive: true,
    globalCategory: "UK",
    streamType: "hls",
  },

  // ================= FRANCE CHANNELS =================
  {
    id: "france24-en",
    name: "France 24 English",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Logo-france-24.png/1200px-Logo-france-24.png",
    url: "https://stream.france24.com/hls/live/2037754/F24_EN_LO_HLS/master_500.m3u8",
    youtubeId: "Fmjxz5iFhvA",
    category: "News",
    country: "FR",
    language: "English",
    isLive: true,
    globalCategory: "France",
    streamType: "hls",
  },
  {
    id: "france24-fr",
    name: "France 24 Français",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Logo-france-24.png/1200px-Logo-france-24.png",
    url: "https://stream.france24.com/hls/live/2037751/F24_FR_LO_HLS/master_500.m3u8",
    category: "News",
    country: "FR",
    language: "French",
    isLive: true,
    globalCategory: "France",
    streamType: "hls",
  },

  // ================= GERMANY CHANNELS =================
  {
    id: "dw-news-de",
    name: "DW News (Deutsche Welle)",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/DW_English_2012_logo.svg/1200px-DW_English_2012_logo.svg.png",
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dl_live_102/master.m3u8",
    youtubeId: "IhgQOlCN7Jw",
    category: "News",
    country: "DE",
    language: "English",
    isLive: true,
    globalCategory: "Germany",
    streamType: "hls",
  },

  // ================= MIDDLE EAST CHANNELS =================
  {
    id: "al-jazeera-me",
    name: "Al Jazeera English",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Al_Jazeera_English_2016_logo.svg/1200px-Al_Jazeera_English_2016_logo.svg.png",
    url: "https://live-hls-web-aje.getaj.net/AJE/03.m3u8",
    youtubeId: "gCNeDWCI0vo",
    category: "News",
    country: "QA",
    language: "English",
    isLive: true,
    globalCategory: "Middle East",
    streamType: "hls",
  },

  // ================= BANGLADESH CHANNELS =================
  {
    id: "jamuna-tv-bd",
    name: "Jamuna TV",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Jamuna_Television_logo.png/640px-Jamuna_Television_logo.png",
    url: "https://edge1.bioscopelive.com/hls/jamuna_tv/index.m3u8",
    youtubeId: "rC_J_W_g4bU",
    category: "News",
    country: "BD",
    language: "Bengali",
    isLive: true,
    globalCategory: "Bangladesh",
    streamType: "hls",
  },
  {
    id: "somoy-tv-bd",
    name: "Somoy TV",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/2/23/Somoy_TV_logo.svg/1200px-Somoy_TV_logo.svg.png",
    url: "https://edge1.bioscopelive.com/hls/somoy_tv/index.m3u8",
    youtubeId: "d653_oVjVbI",
    category: "News",
    country: "BD",
    language: "Bengali",
    isLive: true,
    globalCategory: "Bangladesh",
    streamType: "hls",
  },

  // ================= PAKISTAN CHANNELS =================
  {
    id: "hum-tv-pk",
    name: "HUM News",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/PTV_Logo_2014.svg/1200px-PTV_Logo_2014.svg.png",
    url: "https://edge.crichd.pro/live/hum_news/playlist.m3u8",
    youtubeId: "W7oR0o33w6E",
    category: "News",
    country: "PK",
    language: "Urdu",
    isLive: true,
    globalCategory: "Pakistan",
    streamType: "hls",
  },
]

// Country groups configuration
export const COUNTRIES: CountryChannels[] = [
  {
    name: "India",
    code: "IN",
    emoji: "🇮🇳",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "India"),
  },
  {
    name: "USA",
    code: "US",
    emoji: "🇺🇸",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "USA"),
  },
  {
    name: "UK",
    code: "GB",
    emoji: "🇬🇧",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "UK"),
  },
  {
    name: "France",
    code: "FR",
    emoji: "🇫🇷",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "France"),
  },
  {
    name: "Germany",
    code: "DE",
    emoji: "🇩🇪",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Germany"),
  },
  {
    name: "Middle East",
    code: "ME",
    emoji: "🌍",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Middle East"),
  },
  {
    name: "Bangladesh",
    code: "BD",
    emoji: "🇧🇩",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Bangladesh"),
  },
  {
    name: "Pakistan",
    code: "PK",
    emoji: "🇵🇰",
    channels: GLOBAL_CHANNELS.filter((c) => c.globalCategory === "Pakistan"),
  },
]
